//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNganHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public string MaGD { get; set; }
        public string TenKH { get; set; }
        public string SoTK { get; set; }
        public Nullable<decimal> SoTienGiaoDich { get; set; }
        public string NoiDungGiaoDich { get; set; }
    }
}
