//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNganHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNganHangEntities : DbContext
    {
        public QLNganHangEntities()
            : base("name=QLNganHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LichSuGiaoDich> LichSuGiaoDiches { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SoTietKiem> SoTietKiems { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TinDung> TinDungs { get; set; }
        public virtual DbSet<VayTien> VayTiens { get; set; }
        public virtual DbSet<LaiXuat> LaiXuats { get; set; }
        public virtual DbSet<View_KhachHang> View_KhachHang { get; set; }
        public virtual DbSet<View_VayTien> View_VayTien { get; set; }
    }
}
