//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNganHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoTietKiem
    {
        public string MaSo { get; set; }
        public string TenKH { get; set; }
        public string MaKH { get; set; }
        public string SDT { get; set; }
        public string Cccd { get; set; }
        public Nullable<decimal> TienGui { get; set; }
        public System.DateTime NgayGui { get; set; }
        public int KyHan { get; set; }
        public decimal LaiXuat { get; set; }
        public Nullable<int> DaThanhToan { get; set; }
    }
}
