//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNganHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinDung
    {
        public string MaTD { get; set; }
        public string TenKH { get; set; }
        public Nullable<decimal> ThuNhap { get; set; }
        public string Cccd { get; set; }
        public string LoaiThe { get; set; }
        public decimal HanMuc { get; set; }
        public System.DateTime NgayTra { get; set; }
        public double LaiXuatTD { get; set; }
        public Nullable<decimal> NoTD { get; set; }
        public Nullable<decimal> NoXau { get; set; }
        public string SoLan { get; set; }
    }
}
