//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNganHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class VayTien
    {
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Cccd { get; set; }
        public string DiaChi { get; set; }
        public Nullable<decimal> ThuNhap { get; set; }
        public decimal SoTienVay { get; set; }
        public string HinhThucVay { get; set; }
        public string TaiSanTheChap { get; set; }
        public int KyHan { get; set; }
        public decimal LaiXuat { get; set; }
        public System.DateTime NgayVay { get; set; }
        public System.DateTime NgayTra { get; set; }
        public Nullable<int> NoXau { get; set; }
    }
}
